---
# tasks file for win_package_install

- name: Install multiple packages
  win_chocolatey:
    name: "{{ item.name }}"
    params: "{{ item.param }}"
    state: latest
#  when: ansible_distribution == "Microsoft Windows Server 2012 R2 Standard"
  with_items:
    - "{{ target_packages }}"
  tags:
    - install_package

