---

- name: Add multiple users to windows Active directory
  win_domain_user:
    name: "{{item.name}}"
    firstname: "{{item.firstname}}"
    surname: "{{item.surname}}"
    password: "{{item.password}}"
    email: "{{item.email}}"
    state: present
  with_items:
    - "{{ target_users }}"
  tags:
    - create_user

