---
# tasks file for win_firewall

- name: Firewall rule to allow {{service_name}} on {{protocol_name}} port {{local_port}}
  win_firewall_rule:
    name: "{{ item.name }}"
    localport: "{{ item.port }}"
    protocol: "{{ item.protocol }}"
    action: allow
    direction: in
    state: present
    enabled: yes 
#  when: ansible_distribution == "Microsoft Windows Server 2012 R2 Standard"
  with_items:
    - "{{ target_rules }}"
  tags:
    - enable_firewall 

