---

- name: install openssh on a windows host
  hosts: windows
  become: yes
  gather_facts: false
  vars_files:
    - ssh_var.yml
  roles:
  - win_package_install
  - win_service_manage
  - win_firewall
